### ISSUE TITLE
Mobile input is missing

### ISSUE THREAD

**Issue by Black360o** [ABCxFF/diepcustom-v1#113]
Mobile input is missing

**Comment by Nul-led** [comment]
Can you describe your issue further? What do you mean by mobile input?

**Comment by Black360o** [comment]
The fact is that the client does not work on mobile devices, and this is a big problem for those who only have mobile devices

**Comment by c86ec23b-fef1-4979-b2fa-b9adc351b8cc** [comment]
hopefully this is something we might work on soon

**Comment by c86ec23b-fef1-4979-b2fa-b9adc351b8cc** [comment]
ive been thinking about adding it for a while

**Comment by Nul-led** [comment]
> The fact is that the client does not work on mobile devices, and this is a big problem for those who have only mobile devices

The problem is that the wasm is not suitable for running on mobile devices thus even if we implemented the js part of it, without the wasm it wont be possible.

**Comment by c86ec23b-fef1-4979-b2fa-b9adc351b8cc** [comment]
it is suitable @Nul-led i did it before

**Comment by c86ec23b-fef1-4979-b2fa-b9adc351b8cc** [comment]
remove the asm const that checks for orientation and it will work

**Comment by Altanis** [comment]
> > The fact is that the client does not work on mobile devices, and this is a big problem for those who have only mobile devices
> 
> The problem is that the wasm is not suitable for running on mobile devices thus even if we implemented the js part of it, without the wasm it wont be possible.

untrue, diep.io currently runs on mobile while still using WASM

**Comment by ABCxFF** [comment]
The "wasm" referered to the specific version of the build we use. It is possible though as xScripty mentions, and in the future, efforts might be made to add more support.

**Comment by Nul-led** [comment]
> > > The fact is that the client does not work on mobile devices, and this is a big problem for those who have only mobile devices
> > 
> > The problem is that the wasm is not suitable for running on mobile devices thus even if we implemented the js part of it, without the wasm it wont be possible.
> 
> untrue, diep.io currently runs on mobile while still using WASM

Yea figured so too thanks to xScripty

**Comment by Nul-led** [comment]
wont be added as far as im concerned, mobile with the desktop wasm is very laggy and probably has bugs too..
