### ISSUE TITLE
Mothership leaderboard / invalid fields bug - crashes clients

### ISSUE THREAD

**Issue by Nul-led** [ABCxFF/diepcustom-v1#95]
**What is inconsistent**
0x00 Packet Chunking isnt working 

**Additional notes**
Throws a runtime error every time a chunked 0x00 packet is received

**Comment by ABCxFF** [comment]
I'm not sure if its everytime but this has been observed multiple times now

**Comment by Nul-led** [comment]
@ABCxFF should we do the chunking by collecting 0x00 chunks on the client and push the packet once all chunks are collected then?

**Comment by Nul-led** [comment]
Also i still can't properly reproduce the issue :x
Even when spectating an entire arena of entities, no invalid 0x00 packets get received.. although the server obv chunks the packets

**Comment by ABCxFF** [comment]
More info has led us to find out its likely mothership related.

**Comment by Nul-led** [comment]
should be resolved iirc, reopen if not
